default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: jamby_development
test:
  <<: *default
  database: jamby_test
production:
  <<: *default
  database: jamby_production
